#!/bin/bash                                                                                                       
./update #runs the update script                                                     
sudo chmod +x ./* #gives execute permissions to everything in the parent folder
