#!/bin/bash
# This is a menu template written in bash
# By: MBHudson 2025
#
clear
function Menu_1
{
option=0
until [ "$option" = "1" ]; do
clear
 echo "  1.) Option 1"
 echo "  2.) Option 2"
 echo "  3.) Option 3"
 echo -e "                                                                           \e[41m b.) Main Menu" "\e[49m"
 echo -n "myprogram@nlcc:~#:"
 read option
 echo ""
 case $option in
 1 ) echo "Option 1" ;;
 2 ) echo "Option 2" ;;
 3 ) echo "Option 3" ;;
 b ) main_menu ;;
 * ) tput setf 3;echo "echo -n "myprogram@nlcc:~#:"";tput setf 3;
 esac
 done
}

function Menu_2
{
option=0
until [ "$option" = "2" ]; do
clear
 echo "  1.) Option 1"
 echo "  2.) Option 2"
 echo "  3.) Option 3"
 echo -e "                                                                           \e[41m b.) Main Menu" "\e[49m"
 echo -n "myprogram@nlcc:~#:"
 read option
 echo ""
 case $option in
 1 ) echo "Option 1" ;;
 2 ) echo "Option 2" ;;
 3 ) echo "Option 3" ;;
 b ) main_menu ;;
 * ) tput setf 3;echo "echo -n "myprogram@nlcc:~#:"";tput setf 3;
 esac
 done
}

function Menu_3
{
option=0
until [ "$option" = "3" ]; do
clear
 echo "  1.) Option 1"
 echo "  2.) Option 2"
 echo "  3.) Option 3"
 echo -e "                                                                           \e[41m b.) Main Menu" "\e[49m"
 echo -n "myprogram@nlcc:~#:"
 read option
 echo ""
 case $option in
 1 ) echo "Option 1" ;;
 2 ) echo "Option 2" ;;
 3 ) echo "Option 3" ;;
 b ) main_menu ;;
 * ) tput setf 3;echo "echo -n "myprogram@nlcc:~#:"";tput setf 3;
 esac
 done
}

function main_menu
{
option=0
until [ "$option" = "4" ]; do

clear

 echo -e "\e[91m       1.) Menu 1         2.) Menu 2         3.) Menu 3\e[0m"
echo ""                                   
echo ""                                                           
echo ""
 echo -e -n "\e[38;5;82mmyprogram@\e[38;5;198tnlcc:~#:\e[0m"
read option
echo ""
case $option in
    1 ) Menu_1 ;  ;;
    2 ) Menu_2 ;  ;;
    3 ) Menu_3t ;  ;;
    * ) tput setf 4;echo -n "myprogram@nlcs:~#:";tput setf 4;                    
esac
done
 }
main_menu
